require:
  - rubocop/cop/internal_affairs
  - rubocop-rspec
AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.1

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'
  IgnoredPatterns:
    - '^#*'
  Max: 80

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/EmptyFile:
  Exclude:
    - 'lib/scim/kit/v2/templates/nil_class.json.jbuilder'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'lib/scim/kit/v2/service_provider_configuration.rb'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/scim-kit.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Exclude:
    - 'lib/scim/kit/v2/attribute.rb'

Style/StringLiterals:
  EnforcedStyle: 'single_quotes'

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
